### ISSUE TITLE
[PE-D][Tester C] Command mentioned in UG is identified as invalid - add_tag command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-3/tp#117]
1. The UG mentions an `add_tag` command to add a tag to a particular person. But the app identifies the command to be invalid.

![image.png](https://raw.githubusercontent.com/Flash161203/ped/main/files/3c3b155c-6b1f-4e79-ac78-5bc9ea1d7e50.png)

![image.png](https://raw.githubusercontent.com/Flash161203/ped/main/files/0bae0612-a855-4ff8-a8c0-97b192de320a.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Flash161203/ped#3

**Comment by hhchinh2002** [comment]
duplicated issue with another issue#130
