### ISSUE TITLE
[PE-D][Tester C] Command format mentioned in UG is identified as invalid - tag command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-3/tp#125]
1. When the `tag` command is used in the format mentioned in the UG, the app identifies it as an invalid command.

![image.png](https://raw.githubusercontent.com/Flash161203/ped/main/files/49b5f6c3-c118-4d78-8628-d1b68b35add3.png)

![image.png](https://raw.githubusercontent.com/Flash161203/ped/main/files/53c370f9-2f2e-4326-853e-c9b3df98b605.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Flash161203/ped#5

**Comment by hhchinh2002** [comment]
duplicated with another report at issue#134
