### ISSUE TITLE
[PE-D][Tester B] export and import commands not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-3/tp#126]
Even when I input the correct command as suggested by the user guide, the application is still not responding, and the cursor stuck for more than 2 minutes.
![export.png](https://raw.githubusercontent.com/Emrysil/ped/main/files/bec59a9c-5d6d-43cb-a4b9-fbff66ac01de.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Emrysil/ped#8

**Comment by winsonheng** [comment]
Hi this issue only seems to appear on Mac, and unfortunately my team does not have access to a MacBook for testing. Hence, now that I've fixed the code, may I trouble you to help test the `import` and `export` commands? I only need to know if it crashes or not. Thank you!

Jar download: https://github.com/AY2223S2-CS2103T-T17-3/tp/releases/download/v1.4.0-demo/eLister.jar
Excel file to import: [Insurance List B.csv](https://github.com/AY2223S2-CS2103T-T17-3/tp/files/11184706/Insurance.List.B.csv)
